import _ from 'lodash';
import { test } from 'node:test';
import assert from 'node:assert';
import { runOasTest } from '../../src/tests/runners.js';
import './_setup.js';

// --- Found by running gen against real production connectors in a separate factory repo
// (graphos-service-factory/service-catalog), comparing output against the deployed schema
// generated by a different (Rust) tool. Filed as #85 and #86. ---

test('test_85_first_success_response_is_taken', async () => {
  // #85: a POST whose only documented answer is 201 — the REST convention for "created" — never
  // reached its real schema. visitResponses looked for '200' then 'default', found neither and
  // synthesized `{ success: Boolean }`, discarding the real `Widget` shape with no warning. Found
  // on HubSpot's and PagerDuty's create endpoints; 244 corpus operations were in this state.
  const schema = await runOasTest('response-201-only.yaml', ['post:/widgets>**'], 1, 2);
  assert.ok(schema !== undefined);
  assert.ok(/createWidgets\(input: WidgetInputInput!\): Widget\b/.test(schema!), 'wants the real Widget return type');
  assert.ok(
    /\bid\b/.test(schema!) && /\bname\b/.test(schema!) && /createdAt/.test(schema!),
    'wants the real fields selected',
  );
  assert.ok(!/success: \$\(true\)/.test(schema!), 'must not fall back to the synthetic success response');
});

test('test_86_list_of_plain_values_stays', async () => {
  // #86: a list whose items are a choice of plain values (confluence's
  // `post:/content/convert-ids-to-types` takes `contentIds: array of anyOf [string, number]`) had
  // nothing to select, so the field vanished. Here it was the only property, so the input type came
  // out with no fields at all and rover rejected the syntax. The list reads as `[JSON]` now.
  const schema = await runOasTest('anyof-body-drops-operation.yaml', ['post:/convert>**'], 2, 2);
  assert.ok(schema !== undefined);
  assert.ok(/\$args\.input \{\n\s+ids\n/.test(schema!), 'and sends it');
  assert.ok(/codes: \[JSON\]/.test(schema!), 'the response side keeps its own list of plain values');
  assert.ok(/\n\s+codes\?\n/.test(schema!), 'and selects it');

  // #132: both fields carry the same reason right above them, not just in the console log.
  const reason = 'items in array have mixed array types - returning JSON type';
  assert.ok(
    new RegExp(
      `input InputInput \\{\\n {2}"NEEDS ATTENTION: ${_.escapeRegExp(reason)}"\\n {2}ids: \\[JSON\\]!\\n\\}`,
    ).test(schema!),
    'the body field keeps the note above it',
  );
  assert.ok(
    new RegExp(`"NEEDS ATTENTION: ${_.escapeRegExp(reason)}"\\n\\s+codes: \\[JSON\\]`).test(schema!),
    'the response field carries the same note',
  );
});
